### ISSUE TITLE
Notifications get sent out for each image

### ISSUE THREAD

**Issue by driesvints** [nathanmac/laravel-elixir-imagemin#2]
Instead of notifying one time, the package notifies for each image separately I believe. I'm using the instructions from the npm page for setting up the Gulp file.

![screen shot 2015-02-08 at 15 07 32](https://cloud.githubusercontent.com/assets/594614/6096789/4cfe30cc-afa4-11e4-8be3-a922e23ed3b9.png)

**Comment by nathanmac** [comment]
I've removed the success notification for now. c56834a5822af1821299d868173b748ea3989544
